### ISSUE TITLE
Unable to do player specific mods for addtional players (version 1.0 or up)

### ISSUE THREAD

**Issue by Kirby5464** [XeroOl/notitg-xgml#8]
So, normally you can do something like 
> {44, 1, instant, 200, 'mini', pn = 3}

to enable 200% mini on player 3. But this feature seemed to stop working on the later version of this template but works well on older versions (0.5). 

Side note:
You can still enable mods for all players though.

**Comment by XeroOl** [comment]
Have you made sure that `MAX_PN` is set to large enough in `core/default.xml`?
That's the only thing I can think of. If not, I'll look into the issue.

**Comment by Kirby5464** [comment]
It is set. Still isn't working... But the thing is, like I said before, it works for all players if you have more than 2 players but it won't work for specific players that are not player 1 or 2.
